# This file was auto-generated by the Meta-Programmed Detector on 2025-12-10 01:17:12
# It contains event detection logic dynamically created by an LLM based on provided rules.
# DO NOT EDIT THIS FILE MANUALLY.

from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict

#==============================================================================#
# --- Stage 3: Independent Rule Functions ---
#==============================================================================#

from typing import Dict, List


def rule_1_group_all_logs_that_share_the_exact_same_process_i(log: Dict) -> List[str]:
    """
    Groups all logs that share the exact same Process ID (PID).
    """
    pid = log.get('PID')

    # A PID must exist to form a group. The value can be an integer (including 0),
    # so we explicitly check for None.
    if pid is not None:
        # Format the key as "KEYTYPE_keyvalue"
        return [f"PID_{pid}"]

    # If no PID is found, return an empty list as per the contract.
    return []

from typing import Dict, List, Optional, Set


def rule_2_merge_event_cores_rule_for_ssh_bruteforce_after_in(log: Dict) -> List[str]:
    """
    Identifies authentication failure logs and extracts the source IP ('ip' or 'rhost')
    as a linking key for grouping into a single SSH Brute-Force Campaign.
    """
    # Rule condition: The log must be an authentication failure log.
    # These are identified by a specific set of TemplateIDs.
    auth_failure_template_ids = {1, 4, 7, 8}
    template_id = log.get('TemplateID')

    if template_id not in auth_failure_template_ids:
        return []

    # The linking key is the "Key Source Identifier", which can be in 'ip' or 'rhost'.
    # We use a set to collect unique identifiers to avoid duplicate keys.
    source_identifiers: Set[str] = set()

    # Extract from 'ip' field (Optional[str])
    ip_address: Optional[str] = log.get('ip')
    if ip_address:
        source_identifiers.add(ip_address)

    # Extract from 'rhost' field (List[str])
    remote_hosts: Optional[List[str]] = log.get('rhost')
    if remote_hosts:
        for host in remote_hosts:
            if host:  # Ensure the host string is not empty
                source_identifiers.add(host)

    # Format the collected identifiers into "KEYTYPE_keyvalue" strings.
    # The key type for an IP address or hostname is 'IP'.
    keys = [f"IP_{identifier}" for identifier in source_identifiers]

    return keys

from typing import Dict, List, Set, Optional

def rule_3_merge_event_cores_rule_for_scanning_activity_ident(log: Dict) -> List[str]:
    """
    Identifies potential SSH scanning/probing activity based on specific TemplateIDs
    and extracts the source IP ('ip' or 'rhost') as a linking key.
    """
    # TemplateIDs indicating pre-authentication errors or protocol anomalies
    TARGET_TEMPLATE_IDS: Set[int] = {5, 13, 14, 16, 21, 22, 23, 24, 26}
    
    keys: List[str] = []
    template_id: Optional[int] = log.get('TemplateID')

    # Check if the log's TemplateID matches the rule's criteria
    if template_id in TARGET_TEMPLATE_IDS:
        # Use a set to store unique IP addresses/hosts to avoid duplicate keys from the same log
        source_identifiers = set()

        # Extract from 'ip' field
        ip_address: Optional[str] = log.get('ip')
        if ip_address:
            source_identifiers.add(ip_address)

        # Extract from 'rhost' field, which is a list
        remote_hosts: Optional[List[str]] = log.get('rhost')
        if isinstance(remote_hosts, list):
            for host in remote_hosts:
                if host:  # Ensure the host string is not empty
                    source_identifiers.add(host)
        
        # Format the collected identifiers into the required key format
        for identifier in source_identifiers:
            keys.append(f"IP_{identifier}")
            
    return keys

def rule_4_boundary_rule_by_state_change_an_event_core_contai(log: dict) -> list[str]:
    """
    Identifies a successful authentication log and creates a unique boundary key.
    This prevents merging with preceding brute-force attempts.
    """
    # The rule identifies a successful login primarily by its TemplateID.
    # TemplateID 17 corresponds to 'Accepted password for <*> from <*>'
    if log.get('TemplateID') != 17:
        return []

    keys = []
    # The "Key Source Identifier" is the remote host IP, which might link
    # this success event to previous failed attempts.
    source_ips = set()

    # Extract potential source IPs from 'rhost' (list) and 'ip' (string) fields.
    rhost = log.get('rhost')
    if isinstance(rhost, list):
        for ip in rhost:
            if isinstance(ip, str) and ip:
                source_ips.add(ip)

    ip_addr = log.get('ip')
    if isinstance(ip_addr, str) and ip_addr:
        source_ips.add(ip_addr)

    # For each unique source IP, create a specific "boundary" key.
    # The "SUCCESSFUL_LOGIN_IP" prefix marks a state change and ensures this key
    # is unique, preventing a merge with keys like "IP_..." from brute-force logs.
    for ip in source_ips:
        keys.append(f"SUCCESSFUL_LOGIN_IP_{ip}")

    return keys

from typing import Dict, List, Optional

def rule_5_state_transition_merge__boundary_rule_a_successful(log: Dict) -> List[str]:
    """
    Extracts linking keys for SSH session lifecycle events based on TemplateID.

    - For 'session opened' (ID 18) and 'session closed' (ID 20), the linking key is the PID.
    - For 'disconnect' (ID 19) and 'session closed' (ID 20), the linking key is the remote host (rhost).
    This allows 'session closed' to link to both the preceding 'session opened' via PID and a
    nearly simultaneous 'disconnect' via rhost, even if the PIDs differ.
    """
    keys = []
    template_id = log.get('TemplateID')

    if not isinstance(template_id, int):
        return []

    # Rule applies to session open (18), disconnect (19), and session close (20)
    if template_id not in [18, 19, 20]:
        return []

    # Link 'session opened' (18) and 'session closed' (20) by the same PID
    if template_id in [18, 20]:
        pid = log.get('PID')
        if pid is not None:
            keys.append(f"PID_{pid}")

    # Link 'disconnect' (19) and 'session closed' (20) by the remote host IP
    if template_id in [19, 20]:
        rhosts = log.get('rhost')
        if isinstance(rhosts, list):
            for rhost_ip in rhosts:
                if rhost_ip:  # Ensure the IP string is not empty
                    keys.append(f"RHOST_{rhost_ip}")

    return keys

def rule_6_key_dimension_split_rule_even_if_timestamps_are_cl(log: dict) -> list[str]:
    """
    Extracts keys based on the source identifier ('ip' or 'rhost') to ensure
    activities from different network sources are treated as separate events.
    """
    keys = []

    # Extract the 'ip' field if it exists and is a non-empty string
    ip_address = log.get('ip')
    if isinstance(ip_address, str) and ip_address.strip():
        keys.append(f"IP_{ip_address.strip()}")

    # Extract from the 'rhost' field, which is expected to be a list of strings
    remote_hosts = log.get('rhost')
    if isinstance(remote_hosts, list):
        for host in remote_hosts:
            if isinstance(host, str) and host.strip():
                keys.append(f"RHOST_{host.strip()}")

    return keys

from typing import Dict, List, Optional

def rule_7_event_type_definition_rule_for_max_failures_an_eve(log: Dict) -> List[str]:
    """
    [EVENT TYPE DEFINITION Rule for Max Failures] An 'Event Core' containing the sequence of templates 'message repeated <*> times' (ID: 9), 'Disconnecting: Too many authentication failures' (ID: 10), and 'PAM <*> more authentication failures' (ID: 11) constitutes a complete, self-contained 'Max Authentication Failures Reached' event. This specific sequence represents the server's policy enforcement and should be identified as a distinct event type, which can then be part of a larger 'SSH Brute-Force Campaign'.
    """
    # Define the set of TemplateIDs that constitute the 'Max Authentication Failures Reached' event.
    max_failures_template_ids = {9, 10, 11}

    template_id = log.get('TemplateID')

    # Check if the log's TemplateID is one of the specified IDs.
    if template_id in max_failures_template_ids:
        # If it is, this log is part of the defined event.
        # We return a key that identifies this event type for the orchestrator.
        return ["EVENT_TYPE_Max_Authentication_Failures_Reached"]

    # If the log does not match the criteria, return an empty list.
    return []

from typing import Dict, List


def rule_8_event_type_definition_rule_for_dns_mismatch_an_eve(log: Dict) -> List[str]:
    """
    [EVENT TYPE DEFINITION Rule for DNS Mismatch] An 'Event Core' initiated by a log with `EventTemplate: 'reverse mapping checking ... failed'` (ID: 0) or `EventTemplate: 'Address <*> maps to ... but this does not map back'` (ID: 25) defines a 'DNS Validation Failure' attempt. Merge any subsequent failure or disconnect logs that share the same PID into this event. These events can then be further merged into a larger 'Scanning Activity' event if they share a Source IP with other similar attempts.
    """
    keys = []
    template_id = log.get('TemplateID')

    # Check if the log matches the trigger conditions for a 'DNS Validation Failure' event.
    if template_id in [0, 25]:
        # Extract PID for merging subsequent related logs into this event.
        pid = log.get('PID')
        if pid is not None:
            keys.append(f"PID_{pid}")

        # Extract Source IP for merging this event into a larger 'Scanning Activity'.
        # The 'ip' field is assumed to be the Source IP.
        source_ip = log.get('ip')
        if source_ip:
            keys.append(f"IP_{source_ip}")

    return keys


#==============================================================================#
# --- Stage 4: Main Event Processor Framework ---
#==============================================================================#

from typing import List, Dict, Tuple, Callable, Optional, Set
import collections
from datetime import datetime, timedelta


############################################################
### PROVIDED KEY EXTRACTOR FUNCTIONS (MUST BE USED) ###
############################################################

def rule_1_group_all_logs_that_share_the_exact_same_process_i(log: Dict) -> List[str]:
    """
    Groups all logs that share the exact same Process ID (PID).
    """
    pid = log.get('PID')

    # A PID must exist to form a group. The value can be an integer (including 0),
    # so we explicitly check for None.
    if pid is not None:
        # Format the key as "KEYTYPE_keyvalue"
        return [f"PID_{pid}"]

    # If no PID is found, return an empty list as per the contract.
    return []


def rule_2_merge_event_cores_rule_for_ssh_bruteforce_after_in(log: Dict) -> List[str]:
    """
    Identifies authentication failure logs and extracts the source IP ('ip' or 'rhost')
    as a linking key for grouping into a single SSH Brute-Force Campaign.
    """
    # Rule condition: The log must be an authentication failure log.
    # These are identified by a specific set of TemplateIDs.
    auth_failure_template_ids = {1, 4, 7, 8}
    template_id = log.get('TemplateID')

    if template_id not in auth_failure_template_ids:
        return []

    # The linking key is the "Key Source Identifier", which can be in 'ip' or 'rhost'.
    # We use a set to collect unique identifiers to avoid duplicate keys.
    source_identifiers: Set[str] = set()

    # Extract from 'ip' field (Optional[str])
    ip_address: Optional[str] = log.get('ip')
    if ip_address:
        source_identifiers.add(ip_address)

    # Extract from 'rhost' field (List[str])
    remote_hosts: Optional[List[str]] = log.get('rhost')
    if remote_hosts:
        for host in remote_hosts:
            if host:  # Ensure the host string is not empty
                source_identifiers.add(host)

    # Format the collected identifiers into "KEYTYPE_keyvalue" strings.
    # The key type for an IP address or hostname is 'IP'.
    keys = [f"IP_{identifier}" for identifier in source_identifiers]

    return keys


def rule_3_merge_event_cores_rule_for_scanning_activity_ident(log: Dict) -> List[str]:
    """
    Identifies potential SSH scanning/probing activity based on specific TemplateIDs
    and extracts the source IP ('ip' or 'rhost') as a linking key.
    """
    # TemplateIDs indicating pre-authentication errors or protocol anomalies
    TARGET_TEMPLATE_IDS: Set[int] = {5, 13, 14, 16, 21, 22, 23, 24, 26}
    
    keys: List[str] = []
    template_id: Optional[int] = log.get('TemplateID')

    # Check if the log's TemplateID matches the rule's criteria
    if template_id in TARGET_TEMPLATE_IDS:
        # Use a set to store unique IP addresses/hosts to avoid duplicate keys from the same log
        source_identifiers = set()

        # Extract from 'ip' field
        ip_address: Optional[str] = log.get('ip')
        if ip_address:
            source_identifiers.add(ip_address)

        # Extract from 'rhost' field, which is a list
        remote_hosts: Optional[List[str]] = log.get('rhost')
        if isinstance(remote_hosts, list):
            for host in remote_hosts:
                if host:  # Ensure the host string is not empty
                    source_identifiers.add(host)
        
        # Format the collected identifiers into the required key format
        for identifier in source_identifiers:
            keys.append(f"IP_{identifier}")
            
    return keys


def rule_4_boundary_rule_by_state_change_an_event_core_contai(log: dict) -> list[str]:
    """
    Identifies a successful authentication log and creates a unique boundary key.
    This prevents merging with preceding brute-force attempts.
    """
    # The rule identifies a successful login primarily by its TemplateID.
    # TemplateID 17 corresponds to 'Accepted password for <*> from <*>'
    if log.get('TemplateID') != 17:
        return []

    keys = []
    # The "Key Source Identifier" is the remote host IP, which might link
    # this success event to previous failed attempts.
    source_ips = set()

    # Extract potential source IPs from 'rhost' (list) and 'ip' (string) fields.
    rhost = log.get('rhost')
    if isinstance(rhost, list):
        for ip in rhost:
            if isinstance(ip, str) and ip:
                source_ips.add(ip)

    ip_addr = log.get('ip')
    if isinstance(ip_addr, str) and ip_addr:
        source_ips.add(ip_addr)

    # For each unique source IP, create a specific "boundary" key.
    # The "SUCCESSFUL_LOGIN_IP" prefix marks a state change and ensures this key
    # is unique, preventing a merge with keys like "IP_..." from brute-force logs.
    for ip in source_ips:
        keys.append(f"SUCCESSFUL_LOGIN_IP_{ip}")

    return keys


def rule_5_state_transition_merge__boundary_rule_a_successful(log: Dict) -> List[str]:
    """
    Extracts linking keys for SSH session lifecycle events based on TemplateID.

    - For 'session opened' (ID 18) and 'session closed' (ID 20), the linking key is the PID.
    - For 'disconnect' (ID 19) and 'session closed' (ID 20), the linking key is the remote host (rhost).
    This allows 'session closed' to link to both the preceding 'session opened' via PID and a
    nearly simultaneous 'disconnect' via rhost, even if the PIDs differ.
    """
    keys = []
    template_id = log.get('TemplateID')

    if not isinstance(template_id, int):
        return []

    # Rule applies to session open (18), disconnect (19), and session close (20)
    if template_id not in [18, 19, 20]:
        return []

    # Link 'session opened' (18) and 'session closed' (20) by the same PID
    if template_id in [18, 20]:
        pid = log.get('PID')
        if pid is not None:
            keys.append(f"PID_{pid}")

    # Link 'disconnect' (19) and 'session closed' (20) by the remote host IP
    if template_id in [19, 20]:
        rhosts = log.get('rhost')
        if isinstance(rhosts, list):
            for rhost_ip in rhosts:
                if rhost_ip:  # Ensure the IP string is not empty
                    keys.append(f"RHOST_{rhost_ip}")

    return keys


def rule_6_key_dimension_split_rule_even_if_timestamps_are_cl(log: dict) -> list[str]:
    """
    Extracts keys based on the source identifier ('ip' or 'rhost') to ensure
    activities from different network sources are treated as separate events.
    """
    keys = []

    # Extract the 'ip' field if it exists and is a non-empty string
    ip_address = log.get('ip')
    if isinstance(ip_address, str) and ip_address.strip():
        keys.append(f"IP_{ip_address.strip()}")

    # Extract from the 'rhost' field, which is expected to be a list of strings
    remote_hosts = log.get('rhost')
    if isinstance(remote_hosts, list):
        for host in remote_hosts:
            if isinstance(host, str) and host.strip():
                keys.append(f"RHOST_{host.strip()}")

    return keys


def rule_7_event_type_definition_rule_for_max_failures_an_eve(log: Dict) -> List[str]:
    """
    [EVENT TYPE DEFINITION Rule for Max Failures] An 'Event Core' containing the sequence of templates 'message repeated <*> times' (ID: 9), 'Disconnecting: Too many authentication failures' (ID: 10), and 'PAM <*> more authentication failures' (ID: 11) constitutes a complete, self-contained 'Max Authentication Failures Reached' event. This specific sequence represents the server's policy enforcement and should be identified as a distinct event type, which can then be part of a larger 'SSH Brute-Force Campaign'.
    """
    # Define the set of TemplateIDs that constitute the 'Max Authentication Failures Reached' event.
    max_failures_template_ids = {9, 10, 11}

    template_id = log.get('TemplateID')

    # Check if the log's TemplateID is one of the specified IDs.
    if template_id in max_failures_template_ids:
        # If it is, this log is part of the defined event.
        # We return a key that identifies this event type for the orchestrator.
        return ["EVENT_TYPE_Max_Authentication_Failures_Reached"]

    # If the log does not match the criteria, return an empty list.
    return []


def rule_8_event_type_definition_rule_for_dns_mismatch_an_eve(log: Dict) -> List[str]:
    """
    [EVENT TYPE DEFINITION Rule for DNS Mismatch] An 'Event Core' initiated by a log with `EventTemplate: 'reverse mapping checking ... failed'` (ID: 0) or `EventTemplate: 'Address <*> maps to ... but this does not map back'` (ID: 25) defines a 'DNS Validation Failure' attempt. Merge any subsequent failure or disconnect logs that share the same PID into this event. These events can then be further merged into a larger 'Scanning Activity' event if they share a Source IP with other similar attempts.
    """
    keys = []
    template_id = log.get('TemplateID')

    # Check if the log matches the trigger conditions for a 'DNS Validation Failure' event.
    if template_id in [0, 25]:
        # Extract PID for merging subsequent related logs into this event.
        pid = log.get('PID')
        if pid is not None:
            keys.append(f"PID_{pid}")

        # Extract Source IP for merging this event into a larger 'Scanning Activity'.
        # The 'ip' field is assumed to be the Source IP.
        source_ip = log.get('ip')
        if source_ip:
            keys.append(f"IP_{source_ip}")

    return keys


############################################################
### YOUR IMPLEMENTATION: THE `EventProcessor` CLASS ###
############################################################

class EventProcessor:
    """
    Orchestrates the clustering of log entries into security events using a
    single-pass algorithm based on the Union-Find data structure.

    This class takes a list of logs, processes them chronologically, and
    groups them into events by applying a set of key-extractor rules and
    time-based linking logic.
    """

    def __init__(self, logs: List[Dict]):
        """
        Initializes the EventProcessor with a specific list of logs.

        Args:
            logs: A list of log dictionaries. The logs are expected to have
                  a 'Timestamp' field. The original order and indices of this
                  list are preserved in the final output.
        """
        if not isinstance(logs, list):
            raise TypeError("Input 'logs' must be a list of dictionaries.")
        self.logs: List[Dict] = logs
        self.num_logs: int = len(logs)

        # --- Union-Find Data Structures ---
        # self.parent[i] stores the parent of item i.
        self.parent: List[int] = list(range(self.num_logs))
        # self.size[i] stores the size of the set rooted at i.
        self.size: List[int] = [1] * self.num_logs

        # --- State-Tracking Dictionary ---
        # Maps a linking key to its most recent occurrence.
        # Format: { "key_string": (log_index, timestamp) }
        self.key_state: Dict[str, Tuple[int, datetime]] = {}

    def _find(self, i: int) -> int:
        """
        Finds the representative (root) of the set containing element i,
        with path compression for efficiency.
        """
        if self.parent[i] == i:
            return i
        # Path compression: set parent directly to the root.
        self.parent[i] = self._find(self.parent[i])
        return self.parent[i]

    def _union(self, i: int, j: int) -> None:
        """
        Merges the sets containing elements i and j, using the
        union-by-size optimization.
        """
        root_i = self._find(i)
        root_j = self._find(j)

        if root_i != root_j:
            # Union by size: attach smaller tree to the root of the larger tree.
            if self.size[root_i] < self.size[root_j]:
                root_i, root_j = root_j, root_i  # Ensure root_i is the larger set
            self.parent[root_j] = root_i
            self.size[root_i] += self.size[root_j]

    def cluster_events(self, rule_functions: List[Callable]) -> Tuple[List[List[int]], Dict[int, int]]:
        """
        Clusters logs into events based on rules and time windows.

        This method performs a single pass over the logs (sorted by timestamp)
        and uses the Union-Find algorithm to group related logs.

        Args:
            rule_functions: A list of key-extractor functions to be applied
                            to each log.

        Returns:
            A tuple containing:
            - security_events (List[List[int]]): A list of events, where each
              event is a list of original log indices.
            - log_index_to_event_id (Dict[int, int]): A mapping from a log's
              original index to its assigned event ID.
        """
        # Define flexible time windows for different key types.
        time_windows = {
            'PID': timedelta(minutes=5),
            'IP': timedelta(minutes=30),
            'RHOST': timedelta(minutes=30),
            'SUCCESSFUL_LOGIN_IP': timedelta(minutes=5),
            'EVENT_TYPE': timedelta(days=1),  # Large window for definitional keys
        }
        DEFAULT_WINDOW = timedelta(minutes=1)

        # Ensure logs are processed chronologically while preserving original indices.
        # Create a list of (original_index, log_dict) and sort by timestamp.
        try:
            indexed_logs = sorted(enumerate(self.logs), key=lambda x: x[1]['Timestamp'])
        except KeyError:
            raise ValueError("All logs must contain a 'Timestamp' key for sorting.")
        except TypeError:
            raise TypeError("All 'Timestamp' values must be datetime objects for sorting.")

        # --- Single-Pass Processing ---
        for original_index, log in indexed_logs:
            current_ts = log['Timestamp']
            
            # 1. Extract all keys for the current log using the provided rules.
            current_keys = set()
            for rule in rule_functions:
                try:
                    keys_from_rule = rule(log)
                    if keys_from_rule:
                        current_keys.update(keys_from_rule)
                except Exception:
                    # Gracefully handle potential errors in rule functions.
                    continue

            # 2. Core Clustering Logic: Link to previous logs based on shared keys.
            for key in current_keys:
                # Check if we've seen this key before.
                if key in self.key_state:
                    prev_index, prev_ts = self.key_state[key]

                    # Determine the appropriate time window for this key type.
                    key_type = key.split('_', 1)[0]
                    window = time_windows.get(key_type, DEFAULT_WINDOW)

                    # If the key appeared recently, merge the log sets.
                    if current_ts - prev_ts <= window:
                        self._union(original_index, prev_index)

                # 3. Update State: Always update the state to the most recent
                #    occurrence of the key.
                self.key_state[key] = (original_index, current_ts)

        # --- Finalization: Construct output from the Union-Find structure ---
        # Group log indices by their final cluster representative.
        clusters = collections.defaultdict(list)
        for i in range(self.num_logs):
            root = self._find(i)
            clusters[root].append(i)

        # Format the clusters into the required return format.
        security_events: List[List[int]] = list(clusters.values())
        log_index_to_event_id: Dict[int, int] = {}
        for event_id, event_logs in enumerate(security_events):
            # Sort logs within each event for deterministic output.
            event_logs.sort()
            for log_index in event_logs:
                log_index_to_event_id[log_index] = event_id

        return security_events, log_index_to_event_id


# This list is used by the host system to know which functions to pass to the processor
ALL_RULE_FUNCTIONS = [rule_1_group_all_logs_that_share_the_exact_same_process_i, rule_2_merge_event_cores_rule_for_ssh_bruteforce_after_in, rule_3_merge_event_cores_rule_for_scanning_activity_ident, rule_4_boundary_rule_by_state_change_an_event_core_contai, rule_5_state_transition_merge__boundary_rule_a_successful, rule_6_key_dimension_split_rule_even_if_timestamps_are_cl, rule_7_event_type_definition_rule_for_max_failures_an_eve, rule_8_event_type_definition_rule_for_dns_mismatch_an_eve]
