from typing import Dict, List


def rule_6_timebased_boundary_rule__bruteforce_timeout_an_ssh(log: Dict) -> List[str]:
    """
    Extracts the source IP address from SSH failed authentication logs.

    This rule identifies logs that represent a failed SSH login attempt. The key
    for linking these events, as per the rule, is the source IP address from which
    the attempt originated. This function extracts that IP to be used by the
    orchestrator for time-based grouping.
    """
    keys = []

    # Event templates indicating a failed SSH authentication attempt.
    # These are common templates generated by sshd.
    failed_auth_templates = {
        'Failed password for * from * port * ssh2',
        'pam_unix(sshd:auth): authentication failure; logname=* uid=* euid=* tty=ssh ruser=* rhost=* user=*',
        'Invalid user * from *',
        'Failed publickey for * from * port * ssh2: *',
        'Invalid user * from * port * ssh2'
    }

    event_template = log.get('EventTemplate')

    if event_template in failed_auth_templates:
        source_ip = None

        # 'rhost' (remote host) is a common field for the source IP in sshd logs.
        # It is often parsed as a list.
        rhosts = log.get('rhost')
        if rhosts and isinstance(rhosts, list) and len(rhosts) > 0:
            source_ip = rhosts[0]

        # If 'rhost' is not found, fall back to the generic 'ip' field.
        if not source_ip:
            source_ip = log.get('ip')

        # If a valid source IP was extracted, format it as a key.
        if source_ip:
            keys.append(f"IP_{source_ip}")

    return keys