# This file was auto-generated by the Meta-Programmed Detector on 2025-12-10 00:12:10
# It contains event detection logic dynamically created by an LLM based on provided rules.
# DO NOT EDIT THIS FILE MANUALLY.

from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict

#==============================================================================#
# --- Stage 3: Independent Rule Functions ---
#==============================================================================#

from typing import Dict, List, Optional

def rule_1_group_all_logs_sharing_the_exact_same_process_id_p(log: Dict) -> List[str]:
 """
 Extracts a linking key based on the Process ID (PID).

 This rule groups all logs that share the exact same PID. The presence of a
 PID is considered a strong indicator for creating a foundational 'Event Core'.
 If a log entry contains a PID, a key in the format "PID_<pid_value>" is
 generated. If no PID is present, no key is generated.
 """
 pid = log.get('PID')

 if pid is not None:
 # The rule is absolute and foundational, so a single key is sufficient.
 return [f"PID_{pid}"]

 # If no PID is found in the log entry, return an empty list.
 return []

from typing import Dict, List

def rule_2_merge_event_cores_rule_for_ssh_bruteforcecredentia(log: Dict) -> List[str]:
 """
 [MERGE EVENT CORES Rule for SSH Brute-Force/Credential Stuffing] After initial grouping by PID, identify all 'Event Cores' from the 'sshd' process that contain authentication failure templates (e.g., 'Failed password for <*> from <*>', 'Invalid user <*> from <*>', 'pam_unix(sshd:auth): authentication failure'). If multiple such cores share the exact same Key Source Identifier (Source IP from the 'ip' or 'rhost' field) and occur within a continuous time window (e.g., 30 minutes), merge them into a single logical 'SSH Brute-Force Attempt' event. This rule reconstructs a sustained attack from a single actor that spans multiple server processes.
 """
 # Condition 1: The log must originate from the 'sshd' process.
 if log.get('ProcessName') != 'sshd':
 return []

 # Condition 2: The event template must indicate an authentication failure.
 event_template = log.get('EventTemplate', '')
 failure_signatures = [
 'Failed password for',
 'Invalid user',
 'authentication failure' # Catches 'pam_unix(sshd:auth): authentication failure'
 ]

 if not any(sig in event_template for sig in failure_signatures):
 return []

 # If conditions are met, extract the source IP/host as the linking key.
 keys = []
 source_identifiers = set()

 # Extract identifier from the 'ip' field.
 source_ip = log.get('ip')
 if source_ip:
 source_identifiers.add(source_ip)

 # Extract identifier(s) from the 'rhost' field.
 remote_hosts = log.get('rhost')
 if isinstance(remote_hosts, list):
 for host in remote_hosts:
 if host:
 source_identifiers.add(host)

 # Create a composite key for each unique source identifier found.
 # The key type "SSH_BRUTEFORCE_IP" signals the intent to group these events
 # as a single logical brute-force attempt from a specific source.
 for identifier in source_identifiers:
 keys.append(f"SSH_BRUTEFORCE_IP_{identifier}")

 return keys

from typing import Dict, List

def rule_3_merge_event_cores_rule_for_complete_ssh_session_id(log: Dict) -> List[str]:
 """
 Identifies SSH session start/end events and extracts a composite key
 based on User and Source IP for session correlation.
 """
 event_template = log.get('EventTemplate', '')

 # The rule specifies four key phrases for identifying SSH session events.
 is_session_start = 'Accepted password for user' in event_template or \
 'session opened for user' in event_template
 is_session_end = 'session closed for user' in event_template or \
 'Received disconnect from' in event_template

 # If the log is not a relevant SSH session event, no key can be extracted.
 if not (is_session_start or is_session_end):
 return []

 # The linking key requires both a user and a source IP.
 # Attempt to extract the user. It's typically in the parameters
 # for most, but not all, of these event types.
 user = None
 # Note: 'Received disconnect from' does not contain a user parameter.
 if is_session_start or ('session closed for user' in event_template):
 params = log.get('Parameters')
 if params and len(params) > 0:
 # For these specific templates, the user is the first parameter.
 user = params[0]

 # Attempt to extract the source IP from the log's enriched fields.
 source_ip = log.get('ip')

 # A key can only be generated if both user and source IP are present,
 # as per the rule's "share the same User and Key Source Identifier" clause.
 if user and source_ip:
 user_str = str(user).strip()
 ip_str = str(source_ip).strip()

 # Ensure extracted values are not empty strings before forming the key.
 if user_str and ip_str:
 return [f"USER_IP_{user_str}_{ip_str}"]

 # If either user or IP is missing, no key can be formed for this log.
 return []

from typing import Dict, List

def rule_4_boundary_rule_by_state_change_an_event_core_repres(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by State Change] An 'Event Core' representing a successful
 login ('Accepted password for user') acts as a hard boundary. This function
 identifies such logs and emits a special key to signal the start of a new
 logical event.
 """
 # The rule identifies a successful login by the phrase 'Accepted password for user'.
 # We check the structured 'EventTemplate' field for this pattern.
 event_template = log.get('EventTemplate', '')

 # If the log represents a successful password acceptance, it's a boundary.
 if 'Accepted password for user' in event_template:
 # Return a specific, constant key that the orchestrator will recognize
 # as a signal to create a new group, effectively creating a boundary.
 # This key represents the state change from unauthenticated to authenticated.
 return ['BOUNDARY_STATE_CHANGE_SUCCESS_LOGIN']

 # If the log does not match the boundary condition, this rule does not apply.
 # Return an empty list, allowing other rules to potentially extract keys.
 return []

def rule_5_boundary_rule_by_explicit_disconnect_an_event_core(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by Explicit Disconnect] An 'Event Core' containing a log with the template 'Disconnecting: Too many authentication failures for <*> [preauth]' marks the definitive end of a brute-force sequence from that Key Source Identifier (Source IP) for that time period. Do not merge it with subsequent attempts from the same IP.
 """
 target_template = 'Disconnecting: Too many authentication failures for <*> [preauth]'
 keys = []

 if log.get('EventTemplate') == target_template:
 # The rule identifies the source by IP. We check 'ip' first, then 'rhost'.
 source_ips = []
 
 # Prioritize the 'ip' field.
 ip = log.get('ip')
 if ip:
 source_ips.append(ip)
 else:
 # Fallback to 'rhost' if 'ip' is not present. 'rhost' is a list.
 rhosts = log.get('rhost')
 if isinstance(rhosts, list):
 for rhost_ip in rhosts:
 if rhost_ip:
 source_ips.append(rhost_ip)

 # For each found source IP, create the composite key.
 for source_ip in source_ips:
 # The key links the IP and the specific template to mark this boundary.
 key = f"IP_TEMPLATE_{source_ip}_{target_template}"
 keys.append(key)
 
 return keys

from typing import Dict, List, Optional

def rule_6_key_dimension_split_rule_even_if_sshd_logs_occur_c(log: Dict) -> List[str]:
 """
 [KEY DIMENSION SPLIT Rule] Even if 'sshd' logs occur close in time, if their
 associated 'Event Cores' have different Key Source Identifiers (Source IP),
 they MUST be treated as belonging to separate logical events. Each unique
 Source IP represents a distinct actor and context.
 """
 keys = []
 
 # This rule is specific to logs from the 'sshd' process.
 if log.get('ProcessName') == 'sshd':
 # Use a set to collect unique IPs from various possible fields.
 source_ips = set()

 # The 'ip' field is a primary candidate for the source IP.
 ip = log.get('ip')
 if ip:
 source_ips.add(ip)

 # The 'rhost' field can also contain remote host IPs. It's a list.
 rhosts = log.get('rhost')
 if isinstance(rhosts, list):
 for host in rhosts:
 if host: # Ensure the host string is not empty
 source_ips.add(host)
 
 # For each unique source IP found, create a formatted key.
 # This key will be used by the orchestrator to separate event streams.
 for val in source_ips:
 keys.append(f"IP_{val}")
 
 return keys

from typing import Dict, List

def rule_7_state_transition_boundary_rule_an_event_core_conta(log: Dict) -> List[str]:
 """
 [STATE TRANSITION BOUNDARY Rule] An 'Event Core' containing a log with the template 'pam_unix(sshd:session): session closed for user' marks the definitive end for the logical event associated with that user's session.
 """
 # Define the specific template that signals the end of a user session.
 target_template = 'pam_unix(sshd:session): session closed for user'

 # Check if the log's event template matches the target.
 if log.get('EventTemplate') == target_template:
 # The user's name is the key piece of information for linking.
 # It is expected to be in the 'Parameters' list.
 parameters = log.get('Parameters', [])
 
 # Ensure the parameters list is not empty.
 if parameters:
 # The user is assumed to be the first parameter.
 user = parameters[0]
 
 # Create a key if the user is a non-empty string.
 if isinstance(user, str) and user:
 return [f"USER_{user}"]

 # If the template doesn't match or no user is found, return an empty list.
 return []

from typing import Dict, List, Optional

def rule_8_merge_event_cores_rule_for_connection_probing_iden(log: Dict) -> List[str]:
 """
 Identifies sshd pre-authentication connection errors and extracts the source IP as a linking key.
 """
 # The rule targets specific pre-authentication errors from the 'sshd' process.
 if log.get('ProcessName') != 'sshd':
 return []

 # Define the set of relevant pre-authentication error templates.
 # These templates correspond to the errors mentioned in the rule.
 pre_auth_error_templates = {
 'Did not receive identification string from <*>',
 'Connection closed by <*> [preauth]',
 'fatal: Read from socket failed'
 }

 event_template = log.get('EventTemplate')
 if event_template not in pre_auth_error_templates:
 return []

 # The rule states that events are linked by the "Key Source Identifier (Source IP)".
 source_ip = log.get('ip')
 if not source_ip:
 return []

 # Construct a specific key for this rule to group these events by IP.
 # The key "SSHD_PROBE_IP_{ip}" ensures we only group these specific probe-like events,
 # distinguishing them from other events that might share the same IP.
 key = f"SSHD_PROBE_IP_{source_ip}"
 return [key]

#==============================================================================#
# --- Stage 4: Main Event Processor Framework ---
#==============================================================================#

from typing import List, Dict, Tuple, Callable, Optional, Set
import collections
from datetime import datetime, timedelta

############################################################
### PROVIDED KEY EXTRACTOR FUNCTIONS (MUST BE USED) ###
############################################################

def rule_1_group_all_logs_sharing_the_exact_same_process_id_p(log: Dict) -> List[str]:
 """
 Extracts a linking key based on the Process ID (PID).

 This rule groups all logs that share the exact same PID. The presence of a
 PID is considered a strong indicator for creating a foundational 'Event Core'.
 If a log entry contains a PID, a key in the format "PID_<pid_value>" is
 generated. If no PID is present, no key is generated.
 """
 pid = log.get('PID')

 if pid is not None:
 # The rule is absolute and foundational, so a single key is sufficient.
 return [f"PID_{pid}"]

 # If no PID is found in the log entry, return an empty list.
 return []

def rule_2_merge_event_cores_rule_for_ssh_bruteforcecredentia(log: Dict) -> List[str]:
 """
 [MERGE EVENT CORES Rule for SSH Brute-Force/Credential Stuffing] After initial grouping by PID, identify all 'Event Cores' from the 'sshd' process that contain authentication failure templates (e.g., 'Failed password for <*> from <*>', 'Invalid user <*> from <*>', 'pam_unix(sshd:auth): authentication failure'). If multiple such cores share the exact same Key Source Identifier (Source IP from the 'ip' or 'rhost' field) and occur within a continuous time window (e.g., 30 minutes), merge them into a single logical 'SSH Brute-Force Attempt' event. This rule reconstructs a sustained attack from a single actor that spans multiple server processes.
 """
 # Condition 1: The log must originate from the 'sshd' process.
 if log.get('ProcessName') != 'sshd':
 return []

 # Condition 2: The event template must indicate an authentication failure.
 event_template = log.get('EventTemplate', '')
 failure_signatures = [
 'Failed password for',
 'Invalid user',
 'authentication failure' # Catches 'pam_unix(sshd:auth): authentication failure'
 ]

 if not any(sig in event_template for sig in failure_signatures):
 return []

 # If conditions are met, extract the source IP/host as the linking key.
 keys = []
 source_identifiers = set()

 # Extract identifier from the 'ip' field.
 source_ip = log.get('ip')
 if source_ip:
 source_identifiers.add(source_ip)

 # Extract identifier(s) from the 'rhost' field.
 remote_hosts = log.get('rhost')
 if isinstance(remote_hosts, list):
 for host in remote_hosts:
 if host:
 source_identifiers.add(host)

 # Create a composite key for each unique source identifier found.
 # The key type "SSH_BRUTEFORCE_IP" signals the intent to group these events
 # as a single logical brute-force attempt from a specific source.
 for identifier in source_identifiers:
 keys.append(f"SSH_BRUTEFORCE_IP_{identifier}")

 return keys

def rule_3_merge_event_cores_rule_for_complete_ssh_session_id(log: Dict) -> List[str]:
 """
 Identifies SSH session start/end events and extracts a composite key
 based on User and Source IP for session correlation.
 """
 event_template = log.get('EventTemplate', '')

 # The rule specifies four key phrases for identifying SSH session events.
 is_session_start = 'Accepted password for user' in event_template or \
 'session opened for user' in event_template
 is_session_end = 'session closed for user' in event_template or \
 'Received disconnect from' in event_template

 # If the log is not a relevant SSH session event, no key can be extracted.
 if not (is_session_start or is_session_end):
 return []

 # The linking key requires both a user and a source IP.
 # Attempt to extract the user. It's typically in the parameters
 # for most, but not all, of these event types.
 user = None
 # Note: 'Received disconnect from' does not contain a user parameter.
 if is_session_start or ('session closed for user' in event_template):
 params = log.get('Parameters')
 if params and len(params) > 0:
 # For these specific templates, the user is the first parameter.
 user = params[0]

 # Attempt to extract the source IP from the log's enriched fields.
 source_ip = log.get('ip')

 # A key can only be generated if both user and source IP are present,
 # as per the rule's "share the same User and Key Source Identifier" clause.
 if user and source_ip:
 user_str = str(user).strip()
 ip_str = str(source_ip).strip()

 # Ensure extracted values are not empty strings before forming the key.
 if user_str and ip_str:
 return [f"USER_IP_{user_str}_{ip_str}"]

 # If either user or IP is missing, no key can be formed for this log.
 return []

def rule_4_boundary_rule_by_state_change_an_event_core_repres(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by State Change] An 'Event Core' representing a successful
 login ('Accepted password for user') acts as a hard boundary. This function
 identifies such logs and emits a special key to signal the start of a new
 logical event.
 """
 # The rule identifies a successful login by the phrase 'Accepted password for user'.
 # We check the structured 'EventTemplate' field for this pattern.
 event_template = log.get('EventTemplate', '')

 # If the log represents a successful password acceptance, it's a boundary.
 if 'Accepted password for user' in event_template:
 # Return a specific, constant key that the orchestrator will recognize
 # as a signal to create a new group, effectively creating a boundary.
 # This key represents the state change from unauthenticated to authenticated.
 return ['BOUNDARY_STATE_CHANGE_SUCCESS_LOGIN']

 # If the log does not match the boundary condition, this rule does not apply.
 # Return an empty list, allowing other rules to potentially extract keys.
 return []

def rule_5_boundary_rule_by_explicit_disconnect_an_event_core(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by Explicit Disconnect] An 'Event Core' containing a log with the template 'Disconnecting: Too many authentication failures for <*> [preauth]' marks the definitive end of a brute-force sequence from that Key Source Identifier (Source IP) for that time period. Do not merge it with subsequent attempts from the same IP.
 """
 target_template = 'Disconnecting: Too many authentication failures for <*> [preauth]'
 keys = []

 if log.get('EventTemplate') == target_template:
 # The rule identifies the source by IP. We check 'ip' first, then 'rhost'.
 source_ips = []
 
 # Prioritize the 'ip' field.
 ip = log.get('ip')
 if ip:
 source_ips.append(ip)
 else:
 # Fallback to 'rhost' if 'ip' is not present. 'rhost' is a list.
 rhosts = log.get('rhost')
 if isinstance(rhosts, list):
 for rhost_ip in rhosts:
 if rhost_ip:
 source_ips.append(rhost_ip)

 # For each found source IP, create the composite key.
 for source_ip in source_ips:
 # The key links the IP and the specific template to mark this boundary.
 key = f"IP_TEMPLATE_{source_ip}_{target_template}"
 keys.append(key)
 
 return keys

def rule_6_key_dimension_split_rule_even_if_sshd_logs_occur_c(log: Dict) -> List[str]:
 """
 [KEY DIMENSION SPLIT Rule] Even if 'sshd' logs occur close in time, if their
 associated 'Event Cores' have different Key Source Identifiers (Source IP),
 they MUST be treated as belonging to separate logical events. Each unique
 Source IP represents a distinct actor and context.
 """
 keys = []
 
 # This rule is specific to logs from the 'sshd' process.
 if log.get('ProcessName') == 'sshd':
 # Use a set to collect unique IPs from various possible fields.
 source_ips = set()

 # The 'ip' field is a primary candidate for the source IP.
 ip = log.get('ip')
 if ip:
 source_ips.add(ip)

 # The 'rhost' field can also contain remote host IPs. It's a list.
 rhosts = log.get('rhost')
 if isinstance(rhosts, list):
 for host in rhosts:
 if host: # Ensure the host string is not empty
 source_ips.add(host)
 
 # For each unique source IP found, create a formatted key.
 # This key will be used by the orchestrator to separate event streams.
 for val in source_ips:
 keys.append(f"IP_{val}")
 
 return keys

def rule_7_state_transition_boundary_rule_an_event_core_conta(log: Dict) -> List[str]:
 """
 [STATE TRANSITION BOUNDARY Rule] An 'Event Core' containing a log with the template 'pam_unix(sshd:session): session closed for user' marks the definitive end for the logical event associated with that user's session.
 """
 # Define the specific template that signals the end of a user session.
 target_template = 'pam_unix(sshd:session): session closed for user'

 # Check if the log's event template matches the target.
 if log.get('EventTemplate') == target_template:
 # The user's name is the key piece of information for linking.
 # It is expected to be in the 'Parameters' list.
 parameters = log.get('Parameters', [])
 
 # Ensure the parameters list is not empty.
 if parameters:
 # The user is assumed to be the first parameter.
 user = parameters[0]
 
 # Create a key if the user is a non-empty string.
 if isinstance(user, str) and user:
 return [f"USER_{user}"]

 # If the template doesn't match or no user is found, return an empty list.
 return []

def rule_8_merge_event_cores_rule_for_connection_probing_iden(log: Dict) -> List[str]:
 """
 Identifies sshd pre-authentication connection errors and extracts the source IP as a linking key.
 """
 # The rule targets specific pre-authentication errors from the 'sshd' process.
 if log.get('ProcessName') != 'sshd':
 return []

 # Define the set of relevant pre-authentication error templates.
 # These templates correspond to the errors mentioned in the rule.
 pre_auth_error_templates = {
 'Did not receive identification string from <*>',
 'Connection closed by <*> [preauth]',
 'fatal: Read from socket failed'
 }

 event_template = log.get('EventTemplate')
 if event_template not in pre_auth_error_templates:
 return []

 # The rule states that events are linked by the "Key Source Identifier (Source IP)".
 source_ip = log.get('ip')
 if not source_ip:
 return []

 # Construct a specific key for this rule to group these events by IP.
 # The key "SSHD_PROBE_IP_{ip}" ensures we only group these specific probe-like events,
 # distinguishing them from other events that might share the same IP.
 key = f"SSHD_PROBE_IP_{source_ip}"
 return [key]

############################################################
### YOUR IMPLEMENTATION: EventProcessor CLASS ###
############################################################

class EventProcessor:
 """
 Orchestrates the clustering of logs into security events using a single-pass
 approach with a Union-Find data structure.
 """

 def __init__(self, logs: List[Dict]):
 """
 Initializes the EventProcessor with a list of log entries.

 Args:
 logs: A list of log dictionaries. Each log must have a 'Timestamp' key.
 """
 if not logs:
 self.sorted_logs: List[Dict] = []
 self.original_indices: List[int] = []
 self.num_logs = 0
 return

 # Store original indices and sort logs chronologically for processing.
 indexed_logs = sorted(
 [(log, i) for i, log in enumerate(logs)],
 key=lambda x: x[0]['Timestamp']
 )
 
 self.sorted_logs = [item[0] for item in indexed_logs]
 self.original_indices = [item[1] for item in indexed_logs]
 self.num_logs = len(self.sorted_logs)
 
 # Initialize Union-Find data structures. Each log starts in its own set.
 self.parent = list(range(self.num_logs))
 self.size = [1] * self.num_logs
 
 # State dictionary to track the last seen index and timestamp for each key.
 self.key_state: Dict[str, Dict] = {}
 
 # Time window configuration for different key types.
 self.time_windows = self._get_default_time_windows()
 self.default_time_window = timedelta(minutes=5)

 def _get_default_time_windows(self) -> Dict[str, timedelta]:
 """Defines the time windows for different linking key prefixes."""
 return {
 "PID_": timedelta(minutes=5),
 "SSH_BRUTEFORCE_IP_": timedelta(minutes=30),
 "USER_IP_": timedelta(hours=8),
 "SSHD_PROBE_IP_": timedelta(minutes=15),
 "IP_TEMPLATE_": timedelta(minutes=1),
 "IP_": timedelta(minutes=30),
 "USER_": timedelta(hours=8),
 }

 def _get_time_window(self, key: str) -> timedelta:
 """Retrieves the appropriate time window for a given key."""
 for prefix, window in self.time_windows.items():
 if key.startswith(prefix):
 return window
 return self.default_time_window

 def _find(self, i: int) -> int:
 """
 Finds the representative (root) of the set containing element i,
 with path compression.
 """
 if self.parent[i] == i:
 return i
 self.parent[i] = self._find(self.parent[i])
 return self.parent[i]

 def _union(self, i: int, j: int) -> None:
 """
 Merges the sets containing elements i and j, using union by size.
 """
 root_i = self._find(i)
 root_j = self._find(j)
 if root_i != root_j:
 # Union by size: attach smaller tree under root of larger tree.
 if self.size[root_i] < self.size[root_j]:
 root_i, root_j = root_j, root_i
 self.parent[root_j] = root_i
 self.size[root_i] += self.size[root_j]

 def cluster_events(self, rule_functions: List[Callable]) -> Tuple[List[List[int]], Dict[int, int]]:
 """
 Clusters logs into events using the provided rule functions.

 This method performs a single pass over the chronologically sorted logs.
 For each log, it extracts linking keys, uses them to merge the log with
 recent, related logs, and intelligently handles boundary conditions to
 delimit events.

 Args:
 rule_functions: A list of key extractor functions to be applied to each log.

 Returns:
 A tuple containing:
 - security_events (List[List[int]]): A list of events, where each event
 is a list of original log indices.
 - log_index_to_event_id (Dict[int, int]): A mapping from a log's
 original index to its final event ID.
 """
 if self.num_logs == 0:
 return [], {}

 for i, log in enumerate(self.sorted_logs):
 current_timestamp = log['Timestamp']

 # 1. Get all unique keys from the rule functions.
 all_keys: Set[str] = set()
 for rule_func in rule_functions:
 try:
 all_keys.update(rule_func(log))
 except Exception:
 # Gracefully skip a rule function if it fails.
 pass
 
 # 2. Perform linking based on the current state of keys.
 for key in all_keys:
 if key in self.key_state:
 prev_info = self.key_state[key]
 time_window = self._get_time_window(key)
 if current_timestamp - prev_info['timestamp'] <= time_window:
 self._union(i, prev_info['index'])

 # 3. Identify boundary keys to apply special state-clearing logic.
 boundary_keys: Set[str] = set()
 non_boundary_keys: Set[str] = set()
 is_boundary_log = False
 for key in all_keys:
 # Keys from rules 4, 5, and 7 are treated as boundaries.
 if key.startswith('BOUNDARY_') or \
 key.startswith('IP_TEMPLATE_') or \
 (key.startswith('USER_') and not key.startswith('USER_IP_')):
 boundary_keys.add(key)
 is_boundary_log = True
 else:
 non_boundary_keys.add(key)

 # 4. Update the state for all keys of the current log.
 for key in all_keys:
 self.key_state[key] = {'index': i, 'timestamp': current_timestamp}

 # 5. If it was a boundary log, clear the state of its non-boundary keys.
 # This "consumes" the linking keys, preventing future logs from linking
 # back across this defined boundary.
 if is_boundary_log:
 for key in non_boundary_keys:
 if key in self.key_state:
 del self.key_state[key]

 # 6. Finalize: Group logs by their final cluster representative.
 events_by_root = collections.defaultdict(list)
 for i in range(self.num_logs):
 root = self._find(i)
 original_log_index = self.original_indices[i]
 events_by_root[root].append(original_log_index)
 
 security_events = list(events_by_root.values())
 
 # 7. Create the final mapping from original log index to event ID.
 log_index_to_event_id = {}
 for event_id, event_logs in enumerate(security_events):
 # Sort logs within an event by their original index for consistency.
 event_logs.sort()
 for log_idx in event_logs:
 log_index_to_event_id[log_idx] = event_id
 
 return security_events, log_index_to_event_id

# This list is used by the host system to know which functions to pass to the processor
ALL_RULE_FUNCTIONS = [rule_1_group_all_logs_sharing_the_exact_same_process_id_p, rule_2_merge_event_cores_rule_for_ssh_bruteforcecredentia, rule_3_merge_event_cores_rule_for_complete_ssh_session_id, rule_4_boundary_rule_by_state_change_an_event_core_repres, rule_5_boundary_rule_by_explicit_disconnect_an_event_core, rule_6_key_dimension_split_rule_even_if_sshd_logs_occur_c, rule_7_state_transition_boundary_rule_an_event_core_conta, rule_8_merge_event_cores_rule_for_connection_probing_iden]
