# This file was auto-generated by the Meta-Programmed Detector on 2025-12-09 22:01:15
# It contains event detection logic dynamically created by an LLM based on provided rules.
# DO NOT EDIT THIS FILE MANUALLY.

from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict

#==============================================================================#
# --- Stage 3: Independent Rule Functions ---
#==============================================================================#

from typing import Dict, List, Optional

def rule_1_group_all_logs_that_share_the_exact_same_process_i(log: Dict) -> List[str]:
 """
 Extracts the Process ID (PID) as a linking key if it exists.
 """
 pid = log.get('PID')

 # A PID can be an integer, including 0. We proceed only if it's not None.
 if pid is not None:
 # Format the key as "KEYTYPE_keyvalue"
 return [f"PID_{pid}"]

 # If no PID is found or it is None, return an empty list.
 return []

def rule_2_if_a_unique_highcardinality_session_or_transaction(log: dict) -> list[str]:
 """
 Extracts potential high-cardinality session or transaction identifiers from log parameters.

 This rule identifies parameters that look like unique IDs (e.g., session IDs,
 transaction IDs, request IDs) based on a set of heuristics:
 - They must not be common, blacklisted words (e.g., 'user', 'error').
 - They must have a minimum length to avoid short, common values.
 - They must contain a mix of letters and numbers, a strong indicator of a generated ID.
 - They must not contain spaces or path separators.
 """
 # A blacklist of common, low-cardinality words that are not unique identifiers.
 # This is defined inside the function to keep it self-contained.
 BLACKLISTED_PARAMS = {
 'root', 'user', 'admin', 'guest', 'info', 'warn', 'warning', 'error',
 'debug', 'trace', 'critical', 'fatal', 'failed', 'success', 'successful',
 'denied', 'accepted', 'refused', 'connection', 'session', 'transaction',
 'request', 'response', 'from', 'to', 'port', 'sshd', 'cron', 'sudo',
 'systemd', 'kernel', 'auth', 'daemon', 'local', 'remote', 'invalid',
 'valid', 'none', 'null', 'true', 'false', 'get', 'post', 'put', 'delete',
 'index.html', 'login', 'logout'
 }

 keys = []
 parameters = log.get('Parameters')

 if not parameters or not isinstance(parameters, list):
 return []

 for param in parameters:
 # Ensure param is a non-empty string
 if not isinstance(param, str) or not param.strip():
 continue

 # Heuristic 1: Check against the blacklist.
 if param.lower() in BLACKLISTED_PARAMS:
 continue

 # Heuristic 2: High-cardinality IDs are typically not very short.
 if len(param) < 8:
 continue

 # Heuristic 3: IDs generally do not contain spaces.
 if ' ' in param:
 continue

 # Heuristic 4: Exclude parameters that look like file paths.
 if '/' in param or '\\' in param:
 continue

 # Heuristic 5: A strong indicator of a generated ID is the presence of
 # both letters and numbers. This filters out plain words and simple numeric values.
 has_alpha = any(c.isalpha() for c in param)
 has_digit = any(c.isdigit() for c in param)

 if has_alpha and has_digit:
 # This parameter is a strong candidate for a transaction/session ID.
 # "TXID" is used as a generic key type for such identifiers.
 keys.append(f"TXID_{param}")

 return keys

def rule_3_merge_event_cores_rule_for_ssh_bruteforcescanning_(log: dict) -> list[str]:
 """
 Identifies SSH authentication failures and extracts the source IP/host as a linking key.

 This rule applies if the log entry meets these criteria:
 1. The 'ProcessName' is 'sshd'.
 2. The 'EventTemplate' matches known SSH authentication failure patterns.

 If both conditions are met, the function extracts the source identifier from the
 'ip' or 'rhost' fields to link related brute-force/scanning attempts from the
 same actor, even across different processes.
 """
 process_name = log.get('ProcessName')
 if process_name != 'sshd':
 return []

 failure_templates = {
 'Failed password for *',
 'Invalid user * from *',
 'pam_unix(sshd:auth): authentication failure'
 }
 event_template = log.get('EventTemplate')
 if event_template not in failure_templates:
 return []

 # If conditions are met, extract the source IP(s) as keys.
 # Use a set to handle cases where the same IP is in both 'ip' and 'rhost'.
 keys = set()

 # Extract from the 'ip' field (Optional[str])
 source_ip = log.get('ip')
 if source_ip:
 keys.add(f"IP_{source_ip}")

 # Extract from the 'rhost' field (List[str])
 remote_hosts = log.get('rhost')
 if isinstance(remote_hosts, list):
 for host in remote_hosts:
 if host: # Ensure the host string is not empty or None
 keys.add(f"IP_{host}")

 return list(keys)

from typing import Dict, List, Optional

def rule_4_key_dimension_split_rule_even_if_logs_are_temporal(log: Dict) -> List[str]:
 """
 Extracts keys from 'ip' or 'rhost' fields to identify distinct external actors.
 This forces a split in event cores when the source IP/host changes, as each
 unique source identifier represents a distinct actor and context.
 """
 keys = []

 # The rule identifies 'ip' as a Key Source Identifier for external interactions.
 ip_address = log.get('ip')
 if ip_address and isinstance(ip_address, str):
 keys.append(f"IP_{ip_address}")

 # The rule also identifies 'rhost' as a Key Source Identifier.
 # The 'rhost' field is specified as a list of strings.
 remote_hosts = log.get('rhost')
 if remote_hosts and isinstance(remote_hosts, list):
 for host in remote_hosts:
 # Ensure the item in the list is a valid string before creating a key.
 if host and isinstance(host, str):
 keys.append(f"RHOST_{host}")

 return keys

from typing import Dict, List

def rule_5_boundary_rule_by_state_change__success_an_event_co(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by State Change - Success] An Event Core containing the template
 'Accepted password for <*> from <*>' signifies a successful login. This core
 MUST start a new 'Successful SSH Session' event and must NOT be merged with
 any preceding failure-based events, even if they share the same Key Source
 Identifier and occur within the time window.
 """
 keys = []
 target_template = 'Accepted password for <*> from <*>'

 # Check if the log entry matches the specific success template
 if log.get('EventTemplate') == target_template:
 # The Key Source Identifier for SSH login attempts is the source host/IP.
 # The template 'Accepted password for <user> from <source>' provides this
 # as the second parameter.
 params = log.get('Parameters', [])

 # Ensure we have enough parameters to extract the source identifier
 if len(params) >= 2:
 # The second parameter is the source host/IP
 source_identifier = params[1]

 # Create a unique composite key for this specific success event.
 # This key signals a "boundary" or "state change" to the orchestrator,
 # instructing it to start a new event group and not merge with
 # previous failures from the same source_identifier.
 # The format IP_TEMPLATE_value_template is explicit and robust.
 composite_key = f"IP_TEMPLATE_{source_identifier}_{target_template}"
 keys.append(composite_key)

 return keys

from typing import Dict, List, Optional

def rule_6_state_transition_boundary_rule__session_end_an_eve(log: Dict) -> List[str]:
 """
 [STATE TRANSITION BOUNDARY Rule - Session End] An Event Core containing the template
 'pam_unix(sshd:session): session closed for user <*>' marks the definitive end of a
 'Successful SSH Session' event associated with that session's original PID.
 """
 
 # The specific template that marks the end of a session.
 target_template = 'pam_unix(sshd:session): session closed for user <*>'
 
 # Check if the log entry matches the session closed template.
 if log.get('EventTemplate') == target_template:
 pid = log.get('PID')
 # If the template matches and a PID is present, extract the PID as the key.
 if pid is not None:
 return [f"PID_{pid}"]
 
 return []

from typing import Dict, List, Optional

def rule_7_merge__classify_rule_for_lockout_an_event_core_con(log: Dict) -> List[str]:
 """
 Extracts the PID as a linking key for specific SSH authentication failure templates.
 """
 # Templates related to SSH authentication failures and lockouts.
 relevant_templates = {
 'Disconnecting: Too many authentication failures for <*> [preauth]',
 'message repeated <*> times...',
 'PAM <*> more authentication failures...'
 }

 event_template = log.get('EventTemplate')
 
 # Check if the log's template is one of the specified templates.
 if event_template in relevant_templates:
 pid = log.get('PID')
 # If a PID exists, it's the linking key for this group of events.
 if pid is not None:
 return [f"PID_{pid}"]
 
 return []

from typing import Dict, List

def rule_8_merge__classify_rule_for_connection_errors_an_even(log: Dict) -> List[str]:
 """
 Extracts linking keys for SSH connection error events.

 This rule identifies two types of connection error scenarios:
 1. 'Malformed SSH Packet': Links events related to bad packet length and
 subsequent disconnection from the same source IP.
 2. 'Abrupt Disconnect': Groups fatal socket read/write failures by their
 shared Process ID (PID).
 """
 keys = []
 template = log.get('EventTemplate', '')
 pid = log.get('PID')

 # Part 1: Malformed SSH Packet sequence
 # Rule: "An Event Core containing the sequence of templates 'Bad packet length <*>. [preauth]'
 # followed by 'Disconnecting: Packet corrupt [preauth]' should be defined as a single,
 # complete 'Malformed SSH Packet' event."
 # Logic: These two events are linked by the source IP. We create a specific composite
 # key to allow the orchestrator to group them for this rule.
 malformed_templates = {
 'Bad packet length <*>. [preauth]',
 'Disconnecting: Packet corrupt [preauth]'
 }
 if template in malformed_templates:
 ip_address = log.get('ip')
 if not ip_address:
 rhost = log.get('rhost')
 if rhost and isinstance(rhost, list) and len(rhost) > 0:
 ip_address = rhost[0]

 if ip_address:
 keys.append(f"MALFORMED_PACKET_IP_{ip_address}")

 # Part 2: Abrupt Disconnect events
 # Rule: "...group logs with templates like 'fatal: Read from socket failed...' or
 # 'fatal: Write failed...' by their shared PID to form 'Abrupt Disconnect' events."
 # Logic: If the template indicates a fatal socket error and a PID is present,
 # use the PID as the linking key.
 if template.startswith('fatal: Read from socket failed') or \
 template.startswith('fatal: Write failed'):
 if pid is not None:
 keys.append(f"PID_{pid}")

 return keys

from typing import Dict, List, Optional

def rule_9_merge__classify_rule_for_dns_mismatch_an_event_cor(log: Dict) -> List[str]:
 """
 Extracts the PID as a linking key for logs matching the 'SSH DNS Mismatch Warning' template.
 """
 # The specific template that identifies the 'SSH DNS Mismatch Warning' event.
 target_template = 'Address <*> maps to <*> but this does not map back to the address - POSSIBLE BREAK-IN ATTEMPT!'

 # Check if the log's template matches the target.
 if log.get('EventTemplate') == target_template:
 # The rule requires merging subsequent logs from the same PID.
 # Therefore, the PID is the essential linking key.
 pid = log.get('PID')
 
 # If a PID exists, create and return the key.
 if pid is not None:
 return [f"PID_{pid}"]
 
 # If the template does not match or if the PID is missing, return an empty list.
 return []

def rule_10_timebased_boundary_rule__inactivity_timeout_when_m(log: Dict) -> List[str]:
 # This rule describes a stateful, time-based boundary condition that must be
 # handled by the main orchestrator. The orchestrator is responsible for
 # tracking the time between logs within a correlated event group.
 #
 # A stateless key extractor, by definition, cannot compute time differences
 # or manage the state of an event group because it only inspects a single log
 # in isolation. Therefore, this function does not extract any keys.
 # The time-based logic is applied by the orchestrator using the 'Timestamp'
 # field of the log object itself, after grouping logs by keys from other rules.
 return []

#==============================================================================#
# --- Stage 4: Main Event Processor Framework ---
#==============================================================================#

import collections
import datetime
from typing import Dict, List, Optional, Callable, Tuple, Any

############################################################
### PROVIDED STATELESS KEY EXTRACTOR FUNCTIONS ###
############################################################

def rule_1_group_all_logs_that_share_the_exact_same_process_i(log: Dict) -> List[str]:
 """
 Extracts the Process ID (PID) as a linking key if it exists.
 """
 pid = log.get('PID')

 # A PID can be an integer, including 0. We proceed only if it's not None.
 if pid is not None:
 # Format the key as "KEYTYPE_keyvalue"
 return [f"PID_{pid}"]

 # If no PID is found or it is None, return an empty list.
 return []

def rule_2_if_a_unique_highcardinality_session_or_transaction(log: dict) -> list[str]:
 """
 Extracts potential high-cardinality session or transaction identifiers from log parameters.

 This rule identifies parameters that look like unique IDs (e.g., session IDs,
 transaction IDs, request IDs) based on a set of heuristics:
 - They must not be common, blacklisted words (e.g., 'user', 'error').
 - They must have a minimum length to avoid short, common values.
 - They must contain a mix of letters and numbers, a strong indicator of a generated ID.
 - They must not contain spaces or path separators.
 """
 # A blacklist of common, low-cardinality words that are not unique identifiers.
 # This is defined inside the function to keep it self-contained.
 BLACKLISTED_PARAMS = {
 'root', 'user', 'admin', 'guest', 'info', 'warn', 'warning', 'error',
 'debug', 'trace', 'critical', 'fatal', 'failed', 'success', 'successful',
 'denied', 'accepted', 'refused', 'connection', 'session', 'transaction',
 'request', 'response', 'from', 'to', 'port', 'sshd', 'cron', 'sudo',
 'systemd', 'kernel', 'auth', 'daemon', 'local', 'remote', 'invalid',
 'valid', 'none', 'null', 'true', 'false', 'get', 'post', 'put', 'delete',
 'index.html', 'login', 'logout'
 }

 keys = []
 parameters = log.get('Parameters')

 if not parameters or not isinstance(parameters, list):
 return []

 for param in parameters:
 # Ensure param is a non-empty string
 if not isinstance(param, str) or not param.strip():
 continue

 # Heuristic 1: Check against the blacklist.
 if param.lower() in BLACKLISTED_PARAMS:
 continue

 # Heuristic 2: High-cardinality IDs are typically not very short.
 if len(param) < 8:
 continue

 # Heuristic 3: IDs generally do not contain spaces.
 if ' ' in param:
 continue

 # Heuristic 4: Exclude parameters that look like file paths.
 if '/' in param or '\\' in param:
 continue

 # Heuristic 5: A strong indicator of a generated ID is the presence of
 # both letters and numbers. This filters out plain words and simple numeric values.
 has_alpha = any(c.isalpha() for c in param)
 has_digit = any(c.isdigit() for c in param)

 if has_alpha and has_digit:
 # This parameter is a strong candidate for a transaction/session ID.
 # "TXID" is used as a generic key type for such identifiers.
 keys.append(f"TXID_{param}")

 return keys

def rule_3_merge_event_cores_rule_for_ssh_bruteforcescanning_(log: dict) -> list[str]:
 """
 Identifies SSH authentication failures and extracts the source IP/host as a linking key.

 This rule applies if the log entry meets these criteria:
 1. The 'ProcessName' is 'sshd'.
 2. The 'EventTemplate' matches known SSH authentication failure patterns.

 If both conditions are met, the function extracts the source identifier from the
 'ip' or 'rhost' fields to link related brute-force/scanning attempts from the
 same actor, even across different processes.
 """
 process_name = log.get('ProcessName')
 if process_name != 'sshd':
 return []

 failure_templates = {
 'Failed password for *',
 'Invalid user * from *',
 'pam_unix(sshd:auth): authentication failure'
 }
 event_template = log.get('EventTemplate')
 if event_template not in failure_templates:
 return []

 # If conditions are met, extract the source IP(s) as keys.
 # Use a set to handle cases where the same IP is in both 'ip' and 'rhost'.
 keys = set()

 # Extract from the 'ip' field (Optional[str])
 source_ip = log.get('ip')
 if source_ip:
 keys.add(f"IP_{source_ip}")

 # Extract from the 'rhost' field (List[str])
 remote_hosts = log.get('rhost')
 if isinstance(remote_hosts, list):
 for host in remote_hosts:
 if host: # Ensure the host string is not empty or None
 keys.add(f"IP_{host}")

 return list(keys)

def rule_4_key_dimension_split_rule_even_if_logs_are_temporal(log: Dict) -> List[str]:
 """
 Extracts keys from 'ip' or 'rhost' fields to identify distinct external actors.
 This forces a split in event cores when the source IP/host changes, as each
 unique source identifier represents a distinct actor and context.
 """
 keys = []

 # The rule identifies 'ip' as a Key Source Identifier for external interactions.
 ip_address = log.get('ip')
 if ip_address and isinstance(ip_address, str):
 keys.append(f"IP_{ip_address}")

 # The rule also identifies 'rhost' as a Key Source Identifier.
 # The 'rhost' field is specified as a list of strings.
 remote_hosts = log.get('rhost')
 if remote_hosts and isinstance(remote_hosts, list):
 for host in remote_hosts:
 # Ensure the item in the list is a valid string before creating a key.
 if host and isinstance(host, str):
 keys.append(f"RHOST_{host}")

 return keys

def rule_5_boundary_rule_by_state_change__success_an_event_co(log: Dict) -> List[str]:
 """
 [BOUNDARY Rule by State Change - Success] An Event Core containing the template
 'Accepted password for <*> from <*>' signifies a successful login. This core
 MUST start a new 'Successful SSH Session' event and must NOT be merged with
 any preceding failure-based events, even if they share the same Key Source
 Identifier and occur within the time window.
 """
 keys = []
 target_template = 'Accepted password for <*> from <*>'

 # Check if the log entry matches the specific success template
 if log.get('EventTemplate') == target_template:
 # The Key Source Identifier for SSH login attempts is the source host/IP.
 # The template 'Accepted password for <user> from <source>' provides this
 # as the second parameter.
 params = log.get('Parameters', [])

 # Ensure we have enough parameters to extract the source identifier
 if len(params) >= 2:
 # The second parameter is the source host/IP
 source_identifier = params[1]

 # Create a unique composite key for this specific success event.
 # This key signals a "boundary" or "state change" to the orchestrator,
 # instructing it to start a new event group and not merge with
 # previous failures from the same source_identifier.
 # The format IP_TEMPLATE_value_template is explicit and robust.
 composite_key = f"IP_TEMPLATE_{source_identifier}_{target_template}"
 keys.append(composite_key)

 return keys

def rule_6_state_transition_boundary_rule__session_end_an_eve(log: Dict) -> List[str]:
 """
 [STATE TRANSITION BOUNDARY Rule - Session End] An Event Core containing the template
 'pam_unix(sshd:session): session closed for user <*>' marks the definitive end of a
 'Successful SSH Session' event associated with that session's original PID.
 """
 
 # The specific template that marks the end of a session.
 target_template = 'pam_unix(sshd:session): session closed for user <*>'
 
 # Check if the log entry matches the session closed template.
 if log.get('EventTemplate') == target_template:
 pid = log.get('PID')
 # If the template matches and a PID is present, extract the PID as the key.
 if pid is not None:
 return [f"PID_{pid}"]
 
 return []

def rule_7_merge__classify_rule_for_lockout_an_event_core_con(log: Dict) -> List[str]:
 """
 Extracts the PID as a linking key for specific SSH authentication failure templates.
 """
 # Templates related to SSH authentication failures and lockouts.
 relevant_templates = {
 'Disconnecting: Too many authentication failures for <*> [preauth]',
 'message repeated <*> times...',
 'PAM <*> more authentication failures...'
 }

 event_template = log.get('EventTemplate')
 
 # Check if the log's template is one of the specified templates.
 if event_template in relevant_templates:
 pid = log.get('PID')
 # If a PID exists, it's the linking key for this group of events.
 if pid is not None:
 return [f"PID_{pid}"]
 
 return []

def rule_8_merge__classify_rule_for_connection_errors_an_even(log: Dict) -> List[str]:
 """
 Extracts linking keys for SSH connection error events.

 This rule identifies two types of connection error scenarios:
 1. 'Malformed SSH Packet': Links events related to bad packet length and
 subsequent disconnection from the same source IP.
 2. 'Abrupt Disconnect': Groups fatal socket read/write failures by their
 shared Process ID (PID).
 """
 keys = []
 template = log.get('EventTemplate', '')
 pid = log.get('PID')

 # Part 1: Malformed SSH Packet sequence
 # Rule: "An Event Core containing the sequence of templates 'Bad packet length <*>. [preauth]'
 # followed by 'Disconnecting: Packet corrupt [preauth]' should be defined as a single,
 # complete 'Malformed SSH Packet' event."
 # Logic: These two events are linked by the source IP. We create a specific composite
 # key to allow the orchestrator to group them for this rule.
 malformed_templates = {
 'Bad packet length <*>. [preauth]',
 'Disconnecting: Packet corrupt [preauth]'
 }
 if template in malformed_templates:
 ip_address = log.get('ip')
 if not ip_address:
 rhost = log.get('rhost')
 if rhost and isinstance(rhost, list) and len(rhost) > 0:
 ip_address = rhost[0]

 if ip_address:
 keys.append(f"MALFORMED_PACKET_IP_{ip_address}")

 # Part 2: Abrupt Disconnect events
 # Rule: "...group logs with templates like 'fatal: Read from socket failed...' or
 # 'fatal: Write failed...' by their shared PID to form 'Abrupt Disconnect' events."
 # Logic: If the template indicates a fatal socket error and a PID is present,
 # use the PID as the linking key.
 if template.startswith('fatal: Read from socket failed') or \
 template.startswith('fatal: Write failed'):
 if pid is not None:
 keys.append(f"PID_{pid}")

 return keys

def rule_9_merge__classify_rule_for_dns_mismatch_an_event_cor(log: Dict) -> List[str]:
 """
 Extracts the PID as a linking key for logs matching the 'SSH DNS Mismatch Warning' template.
 """
 # The specific template that identifies the 'SSH DNS Mismatch Warning' event.
 target_template = 'Address <*> maps to <*> but this does not map back to the address - POSSIBLE BREAK-IN ATTEMPT!'

 # Check if the log's template matches the target.
 if log.get('EventTemplate') == target_template:
 # The rule requires merging subsequent logs from the same PID.
 # Therefore, the PID is the essential linking key.
 pid = log.get('PID')
 
 # If a PID exists, create and return the key.
 if pid is not None:
 return [f"PID_{pid}"]
 
 # If the template does not match or if the PID is missing, return an empty list.
 return []

def rule_10_timebased_boundary_rule__inactivity_timeout_when_m(log: Dict) -> List[str]:
 # This rule describes a stateful, time-based boundary condition that must be
 # handled by the main orchestrator. The orchestrator is responsible for
 # tracking the time between logs within a correlated event group.
 #
 # A stateless key extractor, by definition, cannot compute time differences
 # or manage the state of an event group because it only inspects a single log
 # in isolation. Therefore, this function does not extract any keys.
 # The time-based logic is applied by the orchestrator using the 'Timestamp'
 # field of the log object itself, after grouping logs by keys from other rules.
 return []

############################################################
### YOUR IMPLEMENTATION: EventProcessor CLASS ###
############################################################

class EventProcessor:
 """
 Orchestrates the clustering of logs into security events using a single-pass
 approach with a Union-Find data structure.
 """

 def __init__(self, logs: List[Dict[str, Any]]):
 """
 Initializes the EventProcessor with a list of logs.

 Args:
 logs: A list of log dictionaries to be processed. Each dictionary
 must contain a 'Timestamp' key.
 """
 if not isinstance(logs, list):
 raise TypeError("logs must be a list of dictionaries.")
 
 self.logs = logs
 self.num_logs = len(logs)

 # Sort logs by timestamp while preserving their original indices.
 # The Union-Find structure will operate on the indices of this sorted list.
 self.sorted_logs_with_indices: List[Tuple[int, Dict[str, Any]]] = sorted(
 enumerate(self.logs), key=lambda x: x[1]['Timestamp']
 )

 # Initialize Union-Find (Disjoint Set Union) data structures.
 self.parent = list(range(self.num_logs))
 self.set_size = [1] * self.num_logs

 def find(self, i: int) -> int:
 """
 Finds the representative (root) of the set containing element i,
 with path compression optimization.

 Args:
 i: The index of the element.

 Returns:
 The root of the set.
 """
 if self.parent[i] == i:
 return i
 # Path compression
 self.parent[i] = self.find(self.parent[i])
 return self.parent[i]

 def union(self, i: int, j: int) -> None:
 """
 Merges the sets containing elements i and j, using union-by-size
 optimization.

 Args:
 i: The index of the first element.
 j: The index of the second element.
 """
 root_i = self.find(i)
 root_j = self.find(j)

 if root_i != root_j:
 # Union by size: merge smaller set into larger set.
 if self.set_size[root_i] < self.set_size[root_j]:
 root_i, root_j = root_j, root_i
 
 self.parent[root_j] = root_i
 self.set_size[root_i] += self.set_size[root_j]

 def _get_time_window(self, key: str, time_windows: Dict[str, datetime.timedelta], default_window: datetime.timedelta) -> datetime.timedelta:
 """
 Determines the appropriate time window for a given linking key based on its prefix.
 """
 for prefix, window in time_windows.items():
 if key.startswith(prefix):
 return window
 return default_window

 def cluster_events(self, rule_functions: List[Callable]) -> Tuple[List[List[int]], Dict[int, int]]:
 """
 Clusters logs into events based on a set of rule functions and time windows.

 This method performs a single pass over the chronologically sorted logs,
 using the Union-Find algorithm to efficiently group them.

 Args:
 rule_functions: A list of key extractor functions to be applied to each log.

 Returns:
 A tuple containing:
 - security_events (List[List[int]]): A list of events, where each event
 is a list of original log indices.
 - log_index_to_event_id (Dict[int, int]): A mapping from a log's
 original index to its corresponding event ID.
 """
 # Define flexible time windows for different key types.
 time_windows = {
 "PID_": datetime.timedelta(minutes=5),
 "TXID_": datetime.timedelta(minutes=5),
 "IP_": datetime.timedelta(minutes=30),
 "RHOST_": datetime.timedelta(minutes=30),
 "MALFORMED_PACKET_IP_": datetime.timedelta(minutes=1),
 "IP_TEMPLATE_": datetime.timedelta(minutes=30) # For rule 5 boundary
 }
 default_time_window = datetime.timedelta(minutes=15)

 # State tracking dictionary: maps a linking key to the most recent
 # log (as a tuple of its sorted index and timestamp).
 key_state: Dict[str, Tuple[int, datetime.datetime]] = {}

 # --- Single-Pass Processing ---
 for sorted_idx, (original_idx, log) in enumerate(self.sorted_logs_with_indices):
 current_timestamp = log['Timestamp']
 
 # 1. Extract all unique keys for the current log using the provided rules.
 all_keys = set()
 for rule_func in rule_functions:
 try:
 keys = rule_func(log)
 if keys:
 all_keys.update(keys)
 except Exception as e:
 # Gracefully skip a rule function if it fails on a log.
 # In a real system, this would be logged.
 # print(f"Warning: Rule function {rule_func.__name__} failed on log {original_idx}: {e}")
 pass

 # 2. Core Clustering Logic: For each key, check for a recent match.
 for key in all_keys:
 if key in key_state:
 prev_sorted_idx, prev_timestamp = key_state[key]
 
 time_window = self._get_time_window(key, time_windows, default_time_window)
 
 # If the key was seen within the time window, merge the logs' sets.
 if current_timestamp - prev_timestamp <= time_window:
 self.union(sorted_idx, prev_sorted_idx)
 
 # 3. Always update the state to reflect the most recent sighting of the key.
 key_state[key] = (sorted_idx, current_timestamp)

 # --- Finalization ---
 # Group original log indices by their final set representative (root).
 events_by_root = collections.defaultdict(list)
 for sorted_idx in range(self.num_logs):
 root = self.find(sorted_idx)
 original_log_index = self.sorted_logs_with_indices[sorted_idx][0]
 events_by_root[root].append(original_log_index)

 # Format the output into the required tuple structure.
 security_events: List[List[int]] = list(events_by_root.values())
 
 # Sort indices within each event for deterministic and clean output.
 for event in security_events:
 event.sort()

 log_index_to_event_id: Dict[int, int] = {}
 for event_id, event_log_indices in enumerate(security_events):
 for log_idx in event_log_indices:
 log_index_to_event_id[log_idx] = event_id
 
 return security_events, log_index_to_event_id

# This list is used by the host system to know which functions to pass to the processor
ALL_RULE_FUNCTIONS = [rule_1_group_all_logs_that_share_the_exact_same_process_i, rule_2_if_a_unique_highcardinality_session_or_transaction, rule_3_merge_event_cores_rule_for_ssh_bruteforcescanning_, rule_4_key_dimension_split_rule_even_if_logs_are_temporal, rule_5_boundary_rule_by_state_change__success_an_event_co, rule_6_state_transition_boundary_rule__session_end_an_eve, rule_7_merge__classify_rule_for_lockout_an_event_core_con, rule_8_merge__classify_rule_for_connection_errors_an_even, rule_9_merge__classify_rule_for_dns_mismatch_an_event_cor, rule_10_timebased_boundary_rule__inactivity_timeout_when_m]
