# This file was auto-generated by the Meta-Programmed Detector on 2025-12-09 16:33:25
# It contains event detection logic dynamically created by an LLM based on provided rules.
# DO NOT EDIT THIS FILE MANUALLY.

from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict

#==============================================================================#
# --- Stage 3: Independent Rule Functions ---
#==============================================================================#

from typing import Dict, List, Optional

def rule_1_group_all_logs_sharing_the_exact_same_process_id_p(log: Dict) -> List[str]:
    """
    Extracts the Process ID (PID) as a linking key.
    """
    pid = log.get('PID')
    if pid is not None:
        return [f"PID_{pid}"]
    return []

from typing import Dict, List


def rule_2_logs_that_lack_a_pid_such_as_those_from_the_kernel(log: Dict) -> List[str]:
    """
    Identifies logs without a PID and treats them as individual 'Event Cores'.
    An 'Event Core' key is created from the TemplateID and Parameters to group
    identical log lines.
    """
    # The primary condition of the rule is the absence of a PID.
    # The process names mentioned are examples of where this commonly occurs.
    if log.get('PID') is not None:
        return []

    # If the log lacks a PID, we treat it as an "Event Core".
    # We create a highly specific key based on its content (template and parameters)
    # to group it only with other identical log lines.
    template_id = log.get('TemplateID')
    parameters = log.get('Parameters')

    # A meaningful key requires both the template and its parameters.
    if template_id is not None and isinstance(parameters, list):
        # Create a string representation of the parameters.
        params_str = '_'.join(map(str, parameters))

        # Construct the key in the format "KEYTYPE_keyvalue".
        key = f"EVENTCORE_{template_id}_{params_str}"
        return [key]

    return []

from typing import Dict, List, Optional

def rule_3_merge_event_cores_rule_for_network_attackscan_afte(log: Dict) -> List[str]:
    """
    Identifies logs related to network attacks/scans based on specific templates
    and extracts the source IP or rhost as a linking key.
    """
    # Templates indicating a potential network attack or probe
    attack_templates = {
        'authentication failure',
        'check pass; user unknown',
        'connection unexpectedly closed',
        'peer died',
        'probable port-scan',
        'Connection from <*> on illegal port',
        'Kerberos authentication failed'
    }

    event_template = log.get('EventTemplate')

    # If the log's template does not match any of the attack templates, do nothing.
    if not event_template or event_template not in attack_templates:
        return []

    keys = []
    
    # Extract the source IP address if available.
    ip = log.get('ip')
    if ip:
        keys.append(f"IP_{ip}")

    # Extract the remote host FQDN(s) if available.
    rhosts = log.get('rhost')
    if rhosts and isinstance(rhosts, list):
        for host in rhosts:
            if host:  # Ensure the host string is not empty
                keys.append(f"RHOST_{host}")

    return keys

def rule_4_boundary_rule_by_state_change_an_event_core_repres(log: Dict) -> List[str]:
    """
    Identifies a successful login event which acts as a boundary for event correlation.

    This rule detects an 'Event Core' representing a successful login (e.g.,
    'session opened for user'). Such an event must not be merged with preceding
    'Network Attack' events. It signals the start of a new, distinct 'User Session'.
    """
    keys = []
    event_template = log.get('EventTemplate', '')

    if not event_template:
        return []

    # Keywords that indicate a successful login, which initiates a new user session boundary.
    success_login_patterns = [
        "session opened for user",
        "Accepted password for",
        "Accepted publickey for"
    ]

    # Check if the event template contains any of the success patterns.
    if any(pattern in event_template for pattern in success_login_patterns):
        # This key signals to the orchestrator that this log entry is a "state change"
        # and should start a new group, effectively creating a boundary.
        keys.append("STATECHANGE_BOUNDARY_SUCCESSFUL_LOGIN")

    return keys

from typing import Dict, List, Optional

def rule_5_merge_event_cores_rule_for_system_boot_identify_a_(log: Dict) -> List[str]:
    """
    Identifies logs related to a System Boot event based on specific templates,
    process names, or keywords.
    """
    event_template = log.get('EventTemplate', '')
    process_name = log.get('ProcessName', '')

    # Trigger conditions for a system boot event
    is_trigger = (
        event_template == 'syslogd <*>: restart.' or
        event_template == 'Linux version <*>'
    )

    # Merge conditions for logs that should be grouped with the boot event
    is_merge_candidate = (
        process_name == 'kernel' or
        'startup succeeded' in event_template or
        'Version <*> Starting' in event_template or
        'succeeded' in event_template
    )

    # If the log is a trigger or a candidate for merging, tag it for the orchestrator.
    # The orchestrator will handle the stateful logic (time windows, sequence, etc.).
    if is_trigger or is_merge_candidate:
        return ['EVENT_SystemBoot']

    return []

from typing import Dict, List, Optional

def rule_6_merge_event_cores_rule_for_system_shutdown_identif(log: Dict) -> List[str]:
    """
    Identifies logs related to a system shutdown sequence.
    - Tags the trigger log ('shutting down for system reboot').
    - Tags subsequent related logs that indicate shutdown processes.
    """
    keys = []
    event_template = log.get('EventTemplate', '')

    if not event_template:
        return []

    # Rule Part 1: Identify the trigger for a 'System Shutdown' event.
    if event_template == 'shutting down for system reboot':
        # This log is the trigger that starts the shutdown event group.
        # The orchestrator will use this key to initiate a new event.
        keys.append('SYSTEM_SHUTDOWN_TRIGGER')
        # The trigger is also a member of the event group it starts.
        keys.append('SYSTEM_SHUTDOWN_MEMBER')
        return keys

    # Rule Part 2: Identify logs to be merged into an active 'System Shutdown' event.
    merge_keywords = [
        'shutdown succeeded',
        'terminating',
        'exiting',
        'received signal 15',
        '-TERM succeeded'
    ]

    if any(keyword in event_template for keyword in merge_keywords):
        # This log is a member of an ongoing shutdown event. The orchestrator
        # will merge it into the currently active 'System Shutdown' event.
        keys.append('SYSTEM_SHUTDOWN_MEMBER')

    return keys

from typing import Dict, List, Optional

def rule_7_state_transition_boundary_rule_for_sessions_an_eve(log: Dict) -> List[str]:
    """
    Extracts a composite key for session start/end events.

    This rule identifies logs that mark the beginning ('session opened') or
    end ('session closed') of a user session. It creates a linking key
    based on the Process ID (PID) and the username involved, allowing an
    orchestrator to group all logs between these two markers.

    The key format is "PID_USER_{pid}_{username}".
    """
    keys = []
    
    # Safely retrieve necessary fields from the log dictionary
    event_template = log.get('EventTemplate')
    pid = log.get('PID')
    params = log.get('Parameters')

    # The rule requires a template, a PID, and parameters to be present.
    if not event_template or not pid or not params:
        return []

    # Define the specific event templates that mark session boundaries
    start_template = "session opened for user %"
    end_template = "session closed for user %"

    # Check if the current log's template matches one of the boundary markers
    if event_template == start_template or event_template == end_template:
        # The username is expected to be the first parameter for these templates
        if len(params) > 0:
            username = params[0]
            # Create a composite key that uniquely identifies the session
            # by combining the process ID and the username. This same key
            # will be generated for both the "opened" and "closed" events,
            # allowing them to be linked.
            composite_key = f"PID_USER_{pid}_{username}"
            keys.append(composite_key)
            
    return keys

def rule_8_merge_event_cores_rule_for_service_restart_identif(log: Dict) -> List[str]:
    process_name = log.get('ProcessName')
    event_template = log.get('EventTemplate', '')

    if not process_name:
        return []

    # Keywords indicating a service shutdown or startup, derived from the rule's examples.
    # e.g., 'exiting', 'shutdown succeeded', 'starting BIND', 'startup succeeded'
    shutdown_keywords = ['exiting', 'shutdown', 'stopping', 'stopped']
    startup_keywords = ['starting', 'startup', 'started']
    
    relevant_keywords = shutdown_keywords + startup_keywords
    
    lower_template = event_template.lower()

    # If the event template indicates a service start or stop, it's a potential
    # part of a restart event. The ProcessName is the key to link it with its
    # counterpart (shutdown or startup).
    if any(keyword in lower_template for keyword in relevant_keywords):
        return [f"PROCESSNAME_{process_name}"]
            
    return []

from typing import Dict, List, Optional

def rule_9_merge_event_cores_rule_for_kernel_errors_identify_(log: Dict) -> List[str]:
    """
    Extracts keys for kernel error events like page allocation failures,
    stack traces, and out-of-memory kills.
    """
    keys = []
    event_template = log.get('EventTemplate', '')
    process_name = log.get('ProcessName')

    # Part 1: Identify the trigger log with 'page allocation failure'.
    # This key signals the start of a potential kernel panic sequence.
    if 'page allocation failure' in event_template:
        keys.append('EVENT_page_allocation_failure')

    # Part 2: Identify subsequent kernel stack trace logs.
    # The orchestrator will use this key to group contiguous stack traces
    # following a 'page allocation failure' event.
    if process_name == 'kernel' and event_template == '[<*>] <*>+<*>':
        keys.append('EVENT_kernel_stack_trace')

    # Part 3: Identify 'Out of Memory' killer events.
    # The orchestrator will use this common key to group all such events
    # that occur within a specific time window.
    if event_template == 'Out of Memory: Killed process <*>':
        keys.append('EVENT_OutOfMemory_Kill')

    return keys

from typing import Dict, List, Optional

def rule_10_key_dimension_split_rule_when_applying_merging_rul(log: Dict) -> List[str]:
    """
    Extracts keys based on Key Source Identifiers like IP addresses to prevent
    merging events from distinct external actors.
    """
    keys = []

    # Extract the source IP address from the 'ip' field.
    # This identifies a specific external actor.
    ip_address = log.get('ip')
    if ip_address and isinstance(ip_address, str):
        # The presence of a specific IP means this log is tied to that actor.
        keys.append(f"IP_{ip_address}")

    # Extract remote host(s) from the 'rhost' field.
    # This can also identify external actors, especially in logs like sshd.
    remote_hosts = log.get('rhost')
    if remote_hosts and isinstance(remote_hosts, list):
        for host in remote_hosts:
            if host and isinstance(host, str):
                keys.append(f"RHOST_{host}")

    return keys


#==============================================================================#
# --- Stage 4: Main Event Processor Framework ---
#==============================================================================#

import collections
import datetime
from typing import List, Dict, Tuple, Callable, Optional, Any

############################################################
### PHASE 2: STATELESS KEY EXTRACTOR FUNCTIONS (PROVIDED) ###
############################################################

def rule_1_group_all_logs_sharing_the_exact_same_process_id_p(log: Dict) -> List[str]:
    """
    Extracts the Process ID (PID) as a linking key.
    """
    pid = log.get('PID')
    if pid is not None:
        return [f"PID_{pid}"]
    return []

def rule_2_logs_that_lack_a_pid_such_as_those_from_the_kernel(log: Dict) -> List[str]:
    """
    Identifies logs without a PID and treats them as individual 'Event Cores'.
    An 'Event Core' key is created from the TemplateID and Parameters to group
    identical log lines.
    """
    if log.get('PID') is not None:
        return []

    template_id = log.get('TemplateID')
    parameters = log.get('Parameters')

    if template_id is not None and isinstance(parameters, list):
        params_str = '_'.join(map(str, parameters))
        key = f"EVENTCORE_{template_id}_{params_str}"
        return [key]

    return []

def rule_3_merge_event_cores_rule_for_network_attackscan_afte(log: Dict) -> List[str]:
    """
    Identifies logs related to network attacks/scans based on specific templates
    and extracts the source IP or rhost as a linking key.
    """
    attack_templates = {
        'authentication failure',
        'check pass; user unknown',
        'connection unexpectedly closed',
        'peer died',
        'probable port-scan',
        'Connection from <*> on illegal port',
        'Kerberos authentication failed'
    }

    event_template = log.get('EventTemplate')

    if not event_template or event_template not in attack_templates:
        return []

    keys = []
    
    ip = log.get('ip')
    if ip:
        keys.append(f"IP_{ip}")

    rhosts = log.get('rhost')
    if rhosts and isinstance(rhosts, list):
        for host in rhosts:
            if host:
                keys.append(f"RHOST_{host}")

    return keys

def rule_4_boundary_rule_by_state_change_an_event_core_repres(log: Dict) -> List[str]:
    """
    Identifies a successful login event which acts as a boundary for event correlation.
    """
    keys = []
    event_template = log.get('EventTemplate', '')

    if not event_template:
        return []

    success_login_patterns = [
        "session opened for user",
        "Accepted password for",
        "Accepted publickey for"
    ]

    if any(pattern in event_template for pattern in success_login_patterns):
        keys.append("STATECHANGE_BOUNDARY_SUCCESSFUL_LOGIN")

    return keys

def rule_5_merge_event_cores_rule_for_system_boot_identify_a_(log: Dict) -> List[str]:
    """
    Identifies logs related to a System Boot event based on specific templates,
    process names, or keywords.
    """
    event_template = log.get('EventTemplate', '')
    process_name = log.get('ProcessName', '')

    is_trigger = (
        event_template == 'syslogd <*>: restart.' or
        event_template == 'Linux version <*>'
    )

    is_merge_candidate = (
        process_name == 'kernel' or
        'startup succeeded' in event_template or
        'Version <*> Starting' in event_template or
        'succeeded' in event_template
    )

    if is_trigger or is_merge_candidate:
        return ['EVENT_SystemBoot']

    return []

def rule_6_merge_event_cores_rule_for_system_shutdown_identif(log: Dict) -> List[str]:
    """
    Identifies logs related to a system shutdown sequence.
    """
    keys = []
    event_template = log.get('EventTemplate', '')

    if not event_template:
        return []

    if event_template == 'shutting down for system reboot':
        keys.append('SYSTEM_SHUTDOWN_TRIGGER')
        keys.append('SYSTEM_SHUTDOWN_MEMBER')
        return keys

    merge_keywords = [
        'shutdown succeeded',
        'terminating',
        'exiting',
        'received signal 15',
        '-TERM succeeded'
    ]

    if any(keyword in event_template for keyword in merge_keywords):
        keys.append('SYSTEM_SHUTDOWN_MEMBER')

    return keys

def rule_7_state_transition_boundary_rule_for_sessions_an_eve(log: Dict) -> List[str]:
    """
    Extracts a composite key for session start/end events.
    """
    keys = []
    
    event_template = log.get('EventTemplate')
    pid = log.get('PID')
    params = log.get('Parameters')

    if not event_template or not pid or not params:
        return []

    start_template = "session opened for user %"
    end_template = "session closed for user %"

    if event_template == start_template or event_template == end_template:
        if len(params) > 0:
            username = params[0]
            composite_key = f"PID_USER_{pid}_{username}"
            keys.append(composite_key)
            
    return keys

def rule_8_merge_event_cores_rule_for_service_restart_identif(log: Dict) -> List[str]:
    """
    Extracts keys for service restart events based on ProcessName.
    """
    process_name = log.get('ProcessName')
    event_template = log.get('EventTemplate', '')

    if not process_name:
        return []

    relevant_keywords = ['exiting', 'shutdown', 'stopping', 'stopped', 'starting', 'startup', 'started']
    
    lower_template = event_template.lower()

    if any(keyword in lower_template for keyword in relevant_keywords):
        return [f"PROCESSNAME_{process_name}"]
            
    return []

def rule_9_merge_event_cores_rule_for_kernel_errors_identify_(log: Dict) -> List[str]:
    """
    Extracts keys for kernel error events like page allocation failures,
    stack traces, and out-of-memory kills.
    """
    keys = []
    event_template = log.get('EventTemplate', '')
    process_name = log.get('ProcessName')

    if 'page allocation failure' in event_template:
        keys.append('EVENT_page_allocation_failure')

    if process_name == 'kernel' and event_template == '[<*>] <*>+<*>':
        keys.append('EVENT_kernel_stack_trace')

    if event_template == 'Out of Memory: Killed process <*>':
        keys.append('EVENT_OutOfMemory_Kill')

    return keys

def rule_10_key_dimension_split_rule_when_applying_merging_rul(log: Dict) -> List[str]:
    """
    Extracts keys based on Key Source Identifiers like IP addresses to prevent
    merging events from distinct external actors.
    """
    keys = []

    ip_address = log.get('ip')
    if ip_address and isinstance(ip_address, str):
        keys.append(f"IP_{ip_address}")

    remote_hosts = log.get('rhost')
    if remote_hosts and isinstance(remote_hosts, list):
        for host in remote_hosts:
            if host and isinstance(host, str):
                keys.append(f"RHOST_{host}")

    return keys


############################################################
### PHASE 3: STATEFUL ORCHESTRATOR (YOUR IMPLEMENTATION) ###
############################################################

class EventProcessor:
    """
    Clusters a sequence of logs into security events using a single-pass
    approach with a Union-Find data structure.
    """

    def __init__(self, logs: List[Dict[str, Any]]):
        """
        Initializes the EventProcessor with a list of logs.

        Args:
            logs: A list of log dictionaries, assumed to be sorted by timestamp.
        """
        self.logs = logs
        self.num_logs = len(logs)
        self.parent: List[int] = []
        self.size: List[int] = []

    def _find(self, i: int) -> int:
        """
        Finds the root of the set containing element i with path compression.
        """
        if self.parent[i] == i:
            return i
        self.parent[i] = self._find(self.parent[i])
        return self.parent[i]

    def _union(self, i: int, j: int) -> None:
        """
        Merges the sets containing elements i and j using union by size.
        """
        root_i = self._find(i)
        root_j = self._find(j)
        if root_i != root_j:
            if self.size[root_i] < self.size[root_j]:
                root_i, root_j = root_j, root_i
            self.parent[root_j] = root_i
            self.size[root_i] += self.size[root_j]

    def _get_time_window(self, key: str, time_windows_config: Dict[str, datetime.timedelta]) -> datetime.timedelta:
        """
        Determines the appropriate time window for a given linking key.
        """
        for prefix, window in time_windows_config.items():
            if key.startswith(prefix):
                return window
        return time_windows_config['DEFAULT']

    def cluster_events(self, rule_functions: List[Callable]) -> Tuple[List[List[int]], Dict[int, int]]:
        """
        Processes the logs to cluster them into security events.

        Args:
            rule_functions: A list of key extractor functions to be applied to each log.

        Returns:
            A tuple containing:
            - A list of events, where each event is a list of log indices.
            - A dictionary mapping each log index to its corresponding event ID.
        """
        if not self.logs:
            return [], {}

        # 1. Initialization
        self.parent = list(range(self.num_logs))
        self.size = [1] * self.num_logs
        
        key_state: Dict[str, Tuple[int, datetime.datetime]] = {}

        time_windows = {
            'DEFAULT': datetime.timedelta(seconds=30),
            'PID_USER': datetime.timedelta(hours=8),
            'IP': datetime.timedelta(minutes=5),
            'RHOST': datetime.timedelta(minutes=5),
            'EVENT_SystemBoot': datetime.timedelta(minutes=10),
            'SYSTEM_SHUTDOWN': datetime.timedelta(minutes=3),
            'PROCESSNAME': datetime.timedelta(minutes=2),
            'PID': datetime.timedelta(seconds=10),
            'EVENTCORE': datetime.timedelta(seconds=1),
            'EVENT_': datetime.timedelta(minutes=1) # For kernel events etc.
        }

        # 2. Single-Pass Processing
        for i, log in enumerate(self.logs):
            current_ts = log['Timestamp']
            
            all_keys = set()
            for rule in rule_functions:
                try:
                    keys = rule(log)
                    if keys:
                        all_keys.update(keys)
                except Exception:
                    # Gracefully handle potential errors in rule functions
                    continue
            
            # Special handling for boundary logs
            is_boundary = 'STATECHANGE_BOUNDARY_SUCCESSFUL_LOGIN' in all_keys
            
            # 3. Core Clustering Logic
            for key in all_keys:
                # Boundary logs start new events; they don't link to the past.
                if is_boundary:
                    continue

                if key in key_state:
                    prev_index, prev_ts = key_state[key]
                    time_window = self._get_time_window(key, time_windows)
                    
                    if current_ts - prev_ts <= time_window:
                        self._union(i, prev_index)
            
            # Always update the state with the current log's info for each key.
            # For boundary logs, this makes them available for future logs to link to.
            for key in all_keys:
                key_state[key] = (i, current_ts)

        # 4. Finalization
        clusters = collections.defaultdict(list)
        for i in range(self.num_logs):
            root = self._find(i)
            clusters[root].append(i)
            
        security_events = list(clusters.values())
        
        log_index_to_event_id = {}
        for event_id, event_logs in enumerate(security_events):
            for log_index in event_logs:
                log_index_to_event_id[log_index] = event_id
                
        return security_events, log_index_to_event_id


# This list is used by the host system to know which functions to pass to the processor
ALL_RULE_FUNCTIONS = [rule_1_group_all_logs_sharing_the_exact_same_process_id_p, rule_2_logs_that_lack_a_pid_such_as_those_from_the_kernel, rule_3_merge_event_cores_rule_for_network_attackscan_afte, rule_4_boundary_rule_by_state_change_an_event_core_repres, rule_5_merge_event_cores_rule_for_system_boot_identify_a_, rule_6_merge_event_cores_rule_for_system_shutdown_identif, rule_7_state_transition_boundary_rule_for_sessions_an_eve, rule_8_merge_event_cores_rule_for_service_restart_identif, rule_9_merge_event_cores_rule_for_kernel_errors_identify_, rule_10_key_dimension_split_rule_when_applying_merging_rul]
